# Generated by Django 5.2.5 on 2025-09-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Открыта'), (2, 'Приостановлена'), (3, 'Отменена'), (4, 'Закрыта')])),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('contract_type', models.IntegerField(choices=[(1, 'Бессрочный'), (2, 'Срочный'), (3, 'По совместительству'), (4, 'ГПХ')])),
                ('emp_type', models.IntegerField(choices=[(1, 'Полная занятость'), (2, 'Частичная занятость'), (3, 'Временная занятость'), (4, 'Проектная деятельность')])),
                ('work_sced', models.IntegerField(choices=[(1, 'Офис'), (2, 'Гибрид'), (3, 'Удаленная работа')])),
                ('income', models.IntegerField()),
                ('salary_max', models.IntegerField()),
                ('salary_min', models.IntegerField()),
                ('ann_premium', models.IntegerField()),
                ('premium_type', models.IntegerField(choices=[(1, 'Месячное'), (2, 'Квартальное'), (3, 'Годовое')])),
                ('edu_level', models.IntegerField(choices=[(1, 'Б/о'), (2, 'Среднее'), (3, 'Средне-специальное'), (4, 'Высшее')])),
                ('experience', models.IntegerField()),
                ('software_knowledges', models.CharField(max_length=255)),
                ('software_skills', models.CharField(max_length=255)),
                ('foreign_langs', models.CharField(max_length=255)),
                ('allow_trip', models.IntegerField(choices=[(1, 'Да'), (2, 'Редко'), (3, 'Нет')])),
                ('change_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='VacancyReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duties', models.TextField()),
                ('requirements', models.TextField()),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skydev_app.vacancy')),
            ],
        ),
    ]
