# Generated by Django 5.2.5 on 2025-09-07 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0002_vacancy_vacancyreq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255)),
                ('contacts', models.TextField()),
                ('status', models.IntegerField(choices=[(1, 'Ищет работу'), (2, 'Рассматривает предложения'), (3, 'Не готов общаться')])),
                ('photo', models.ImageField(upload_to='')),
                ('foreign_langs', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmpProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specs', models.TextField()),
                ('contract_type', models.IntegerField(choices=[(1, 'Бессрочный'), (2, 'Срочный'), (3, 'По совместительству'), (4, 'ГПХ')])),
                ('emp_type', models.IntegerField(choices=[(1, 'Полная занятость'), (2, 'Частичная занятость'), (3, 'Временная занятость'), (4, 'Проектная деятельность')])),
                ('work_sced', models.IntegerField(choices=[(1, 'Офис'), (2, 'Гибрид'), (3, 'Удаленная работа')])),
                ('software_knowledges', models.CharField(max_length=255)),
                ('software_skills', models.CharField(max_length=255)),
                ('allow_trip', models.IntegerField(choices=[(1, 'Да'), (2, 'Редко'), (3, 'Нет')])),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skydev_app.candidate')),
            ],
        ),
    ]
