# Generated by Django 5.2.5 on 2025-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skydev_app', '0003_candidate_empprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancyreq',
            name='whois',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
